# Multiclass SVM 구현

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [19]:
def standardization(train, test):
    scaler = StandardScaler()
    train = scaler.fit_transform(train)
    test = scaler.transform(test)
    return train, test

X_train, X_test = standardization(X_train, X_test)

In [20]:
X_train

array([[ 0.78522493,  0.32015325,  0.77221097,  1.04726529],
       [-0.26563371, -1.29989934,  0.0982814 , -0.11996537],
       [ 0.43493872,  0.78302542,  0.94069336,  1.43634218],
       [-0.84944407,  0.78302542, -1.24957775, -1.28719604],
       [-0.38239578, -1.7627715 ,  0.15444219,  0.13941922],
       [ 0.55170079, -0.374155  ,  1.05301496,  0.7878807 ],
       [ 0.31817664, -0.14271892,  0.65988937,  0.7878807 ],
       [ 0.20141457, -0.374155  ,  0.43524618,  0.39880381],
       [-1.66677857, -0.14271892, -1.36189934, -1.28719604],
       [-0.14887164, -0.60559109,  0.21060299,  0.13941922],
       [-0.14887164, -1.06846325, -0.12636179, -0.24965767],
       [ 0.31817664, -0.60559109,  0.15444219,  0.13941922],
       [ 0.66846286, -0.83702717,  0.88453256,  0.91757299],
       [ 0.0846525 , -0.14271892,  0.77221097,  0.7878807 ],
       [-0.49915786, -0.14271892,  0.43524618,  0.39880381],
       [-0.26563371, -0.60559109,  0.65988937,  1.04726529],
       [ 2.18636979,  1.

In [21]:
X_test

array([[-0.14887164, -0.374155  ,  0.26676379,  0.13941922],
       [ 0.31817664, -0.60559109,  0.54756778,  0.00972692],
       [ 0.31817664, -1.06846325,  1.05301496,  0.26911151],
       [-1.5500165 , -1.7627715 , -1.36189934, -1.15750374],
       [ 0.0846525 ,  0.32015325,  0.60372857,  0.7878807 ],
       [ 0.78522493, -0.14271892,  0.99685416,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.24957775, -1.15750374],
       [ 0.20141457, -0.14271892,  0.60372857,  0.7878807 ],
       [-0.38239578,  2.63451409, -1.30573855, -1.28719604],
       [-0.38239578, -1.29989934,  0.15444219,  0.13941922],
       [ 0.66846286,  0.08871717,  0.99685416,  0.7878807 ],
       [-0.38239578,  1.0144615 , -1.36189934, -1.28719604],
       [-0.49915786,  0.78302542, -1.13725615, -1.28719604],
       [ 0.43493872, -0.60559109,  0.60372857,  0.7878807 ],
       [ 0.55170079, -1.7627715 ,  0.37908538,  0.13941922],
       [ 0.55170079,  0.55158933,  0.54756778,  0.52849611],
       [-1.19973028,  0.

In [22]:
y_train.unique()

array(['virginica', 'versicolor', 'setosa'], dtype=object)

## One-vs-One(OvO) & One-vs-Rest(OvR)

### 1. one vs one
: 클래스 간의 조합마다 하나의 이진 분류기를 훈련시키는 방식 -> n(n-1)/2만큼 이진 분류기 생성됨<br>
  ex) 3개의 클래스 (A, B, C) -> A vs B, A vs C, B vs C
  - 새로운 데이터 포인트에 대한 예측 수행시, 모든 이진 분류기에서 가장 많이 선택된 클래스 최종으로 선택

### 2. one vs rest
: 각 클래스에 대해 하나의 이진 분류기를 훈련시키는 방식 -> 클래스의 수만큼 이진 분류기 샡성됨<br>
    ex) 3개의 클래스 (A, B, C) -> A vs (B, C), B vs (A, C), C vs (A, B)
    - 새로운 데이터 포인트에 대한 예측 수행시, 각 이진 분류기에서 가장 높은 결정 함수 값을 갖는 클래스 선택됨

In [23]:
y_train = pd.get_dummies(y_train)
y_train

setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
..      ...         ...        ...
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [27]:
svm1 = SVC()
svm2 = SVC()
svm3 = SVC()

SVC()

In [28]:
svm1.fit(X_train, y_train.iloc[:, 0]) # Setosa vs (Versicolor, Virginica)
svm2.fit(X_train, y_train.iloc[:, 1]) # Versicolor vs (Setosa, Virginica)
svm3.fit(X_train, y_train.iloc[:, 2]) # Virsinica vs (Setosa, Versicolor)

SVC()

In [30]:
decision_func1 = svm1.decision_function(X_test)
decision_func2 = svm2.decision_function(X_test)
decision_func3 = svm3.decision_function(X_test)

In [31]:
decision_func1

array([-1.12800812, -1.16251843, -1.1422978 , -0.08568098, -1.17027451,
       -1.23267582,  1.09183692, -1.2512859 ,  1.02069728, -1.2643363 ,
       -1.23088294,  1.10969518,  1.09329371, -1.25623518, -1.04702622,
       -1.12673257,  1.1923107 , -1.02360898, -1.15249844, -1.1523064 ,
        0.88066583, -1.22401144, -1.21240853, -1.14948774, -1.13066337,
        1.17327079,  1.04484236, -1.03358459, -1.13006558, -1.02256327])

In [32]:
decision_func2

array([ 1.22902861,  1.18021327, -0.17897727, -0.18270157,  0.11157081,
       -0.62302972, -1.30208112, -0.1161839 , -1.11408288,  0.98146982,
       -0.50352989, -1.22949294, -1.09831885, -0.35890882,  0.58081027,
        0.69274083, -1.43031588,  1.07405999,  0.047718  , -1.42480972,
       -1.11371034, -0.89665337,  0.04194481,  0.8041226 , -0.32973119,
       -1.43978879, -1.02086281, -1.26618241, -1.86832122,  1.23359629])

In [33]:
decision_func3

array([-1.42708779, -1.21748862,  0.15658044, -0.9341312 , -0.13715909,
        0.77015558, -1.1852678 ,  0.18563113, -1.0405367 , -0.99876073,
        0.64733162, -1.33283373, -1.49025247,  0.45890847, -0.65925536,
       -0.69718272, -1.26836718, -1.17659977, -0.03926931,  1.53339216,
       -1.12083008,  1.03585352,  0.11634206, -0.71111991,  0.41357359,
       -1.2021444 , -1.55142381,  1.2333595 ,  1.84275195, -1.57732042])

In [40]:
iris = []
for i in range(len(decision_func1)):
    iris.append(np.argmax([decision_func1[i], decision_func2[i], decision_func3[i]]))
print(iris)

[1, 1, 2, 0, 1, 2, 0, 2, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1]


In [41]:
y_pred = pd.DataFrame(iris, index=y_test.index).replace({0:"setosa", 1:"versicolor", 2:"virginica"})
y_pred

0
96   versicolor
73   versicolor
134   virginica
41       setosa
70   versicolor
116   virginica
19       setosa
138   virginica
33       setosa
89   versicolor
137   virginica
36       setosa
20       setosa
126   virginica
87   versicolor
56   versicolor
11       setosa
62   versicolor
72   versicolor
120   virginica
8        setosa
147   virginica
77    virginica
86   versicolor
129   virginica
4        setosa
31       setosa
136   virginica
132   virginica
88   versicolor

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9666666666666667